FROM golang:1.20 AS builder
WORKDIR /go/src 
ENV GO111MODULE=on GOPROXY=https://goproxy.cn CGO_ENABLED=0   
ADD . .
RUN go mod tidy && go build -tags netgo -o /bin/pulsar_function cmd/pulsar/pulsar_function.go

FROM alpine:3.10
COPY --from=builder /bin/pulsar_function /
ENTRYPOINT ["/pulsar_function","--fun=false"]