name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        # go-version: ${{ matrix.go }}
        go-version-file: go/go.mod

    - name: Build
      run: cd go && go build -v ./...

    - name: Test
      run: |
        docker run -it -d  --name prometheus --network=host quay.io/prometheus/prometheus:v3.1.0 
        docker ps 
        docker logs prometheus
        cd go && go test -v ./...
